/**
 * generate-tldraw-enums.ts
 *
 * 从 @tldraw/tlschema 的 Default*Style 导出反射枚举值，生成：
 *   1. shared/rpc/generated/tldraw-enums.ts  — Zod enum 定义
 *   2. skill/tldraw-cli/references/generated/enum-tables.md  — Markdown 速查表
 *
 * 运行：npx tsx scripts/codegen/generate-tldraw-enums.ts
 * CI 校验：npm run codegen:check
 */
import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '../..')

// ——— 1. 从 tlschema 反射枚举值 ———

const tlschema = await import('@tldraw/tlschema')

interface StylePropLike {
	values?: readonly string[]
}

function extractValues(style: unknown, name: string): string[] | null {
	if (!style || typeof style !== 'object') {
		process.stderr.write(`[codegen] warn: ${name} is not an object, skipping\n`)
		return null
	}
	const s = style as StylePropLike
	if (!Array.isArray(s.values)) {
		process.stderr.write(`[codegen] warn: ${name}.values is not an array, skipping\n`)
		return null
	}
	return [...s.values] as string[]
}

const styleDefs: Array<{ key: string; exportName: string; source: string }> = [
	{
		key: 'ArrowShapeArrowheadStartStyle',
		exportName: 'ArrowheadEnum',
		source: 'arrow shape 的 arrowheadStart / arrowheadEnd',
	},
	{ key: 'DefaultFillStyle', exportName: 'FillEnum', source: 'geo/arrow shape 的 fill' },
	{ key: 'DefaultDashStyle', exportName: 'DashEnum', source: 'arrow/geo shape 的 dash' },
	{
		key: 'DefaultColorStyle',
		exportName: 'ColorEnum',
		source: '所有 shape 的 color / labelColor',
	},
	{ key: 'GeoShapeGeoStyle', exportName: 'GeoEnum', source: 'geo shape 的 geo' },
	{ key: 'DefaultFontStyle', exportName: 'FontEnum', source: 'text/note/geo shape 的 font' },
	{ key: 'DefaultSizeStyle', exportName: 'SizeEnum', source: 'text/note/geo shape 的 size' },
	{
		key: 'DefaultTextAlignStyle',
		exportName: 'TextAlignEnum',
		source: 'text/geo/note shape 的 textAlign/align',
	},
	{
		key: 'DefaultVerticalAlignStyle',
		exportName: 'VerticalAlignEnum',
		source: 'geo/note shape 的 verticalAlign',
	},
]

interface EnumDef {
	exportName: string
	source: string
	values: string[]
}

const styleMap: Record<string, EnumDef> = {}

for (const def of styleDefs) {
	const style = (tlschema as Record<string, unknown>)[def.key]
	const values = extractValues(style, def.key)
	if (values) {
		styleMap[def.exportName] = { exportName: def.exportName, source: def.source, values }
	}
}

const enumCount = Object.keys(styleMap).length
if (enumCount === 0) {
	process.stderr.write(
		'[codegen] error: failed to reflect any enums from @tldraw/tlschema\n',
	)
	process.exit(1)
}

// 升级漂移防护：打印覆盖统计（不 hard fail，只警告）
const totalProps = Object.values(styleMap).reduce((sum, def) => sum + def.values.length, 0)
process.stdout.write(
	`[codegen] ${totalProps} values covered across ${enumCount} enum types\n`,
)

// ——— 2. 生成 TS 产物 ———

const TS_BANNER = `// Generated by scripts/codegen/generate-tldraw-enums.ts
// Do not edit manually. Run \`npm run codegen\` after upgrading @tldraw/tlschema.

import { z } from 'zod'
`

const tsLines: string[] = [TS_BANNER]

for (const [, def] of Object.entries(styleMap)) {
	const valuesStr = def.values.map((v) => `\t"${v}"`).join(',\n')
	tsLines.push(`/** 来源：${def.source} */`)
	tsLines.push(`export const ${def.exportName} = z.enum([`)
	tsLines.push(valuesStr + ',')
	tsLines.push(`])`)
	tsLines.push(
		`export type ${def.exportName.replace('Enum', '')} = z.infer<typeof ${def.exportName}>`,
	)
	tsLines.push('')
}

const tsOutDir = resolve(ROOT, 'shared/rpc/generated')
mkdirSync(tsOutDir, { recursive: true })
writeFileSync(resolve(tsOutDir, 'tldraw-enums.ts'), tsLines.join('\n'), 'utf-8')
process.stdout.write('[codegen] wrote shared/rpc/generated/tldraw-enums.ts\n')

// ——— 3. 生成 Markdown 产物 ———

const MD_BANNER = `<!-- Generated by scripts/codegen/generate-tldraw-enums.ts -->
<!-- Do not edit manually. Run \`npm run codegen\` after upgrading @tldraw/tlschema. -->

# tldraw 枚举全集

所有枚举值从 \`@tldraw/tlschema\` 的 Default*Style 自动派生。shape-reference.md 引用此文件，不再手写枚举列表。

`

const mdLines: string[] = [MD_BANNER]

for (const [, def] of Object.entries(styleMap)) {
	const enumKey = def.exportName.replace('Enum', '').toLowerCase()
	const count = def.values.length
	mdLines.push(`## ${enumKey}（${count} 种）`)
	mdLines.push('')
	mdLines.push(`**来源**：${def.source}`)
	mdLines.push('')
	mdLines.push(def.values.map((v) => `\`${v}\``).join(' '))
	mdLines.push('')
}

const mdOutDir = resolve(ROOT, 'skill/tldraw-cli/references/generated')
mkdirSync(mdOutDir, { recursive: true })
writeFileSync(resolve(mdOutDir, 'enum-tables.md'), mdLines.join('\n'), 'utf-8')
process.stdout.write('[codegen] wrote skill/tldraw-cli/references/generated/enum-tables.md\n')
